// Recognize untouched tutorial text saved by versions before language settings.
export const legacyTutorialMessages = {
  "# 本周客户回访简报\n\n本周收集 **8 份回访**，平均评分 **3.50 / 5**；其中 4 份评分不高于 3。评分量表为 1–5 分，5 分最高。\n\n## 主要发现\n- **响应时效值得优先关注**：3 份反馈，平均 2.67 分。C01、C03、C06 希望缩短等待或明确预计回复时间。\n- **培训资料整体评价较好**：3 份反馈，平均 4.33 分。C02、C08 希望补充案例和索引。\n- **问题流转可以更清楚**：2 份反馈，平均 3.50 分。C04 希望知道当前处理人。\n\n## 下周行动建议\n1. 由客服组长试行预计回复时间和处理人提示，下周回看相关反馈。\n2. 由培训负责人补充一个常见案例和问题索引，在下次回访时收集评价。\n\n依据：客户回访.csv → summary.csv / findings.md。": "# Weekly customer feedback brief\n\nThis week’s **8 interviews** have an average rating of **3.50 / 5**; 4 ratings are at or below 3. Ratings use a 1–5 scale, with 5 the highest.\n\n## Key findings\n- **Response time needs priority attention**: 3 interviews averaging 2.67. C01, C03, and C06 want shorter waits or estimated response times.\n- **Training materials are well received**: 3 interviews averaging 4.33. C02 and C08 request examples and an index.\n- **Issue handoffs could be clearer**: 2 interviews averaging 3.50. C04 wants to know the current owner.\n\n## Proposed actions for next week\n1. The support lead should trial response-time estimates and owner indicators, then review feedback next week.\n2. The training owner should add a common example and FAQ index, then gather feedback in the next interviews.\n\nSource: customer-feedback.csv → summary.csv / findings.md.",
  "读取客户回访.csv，按整理计划和简报规范计算总样本数、平均评分、主题分布和评分不高于 3 的数量。用 Python 完成统计并核对各主题合计。": "Read customer-feedback.csv. Following the plan and brief requirements, calculate the sample size, average rating, topic distribution, and number of ratings at or below 3. Use Python and verify the topic totals.",
  "在 Result 目录写出 summary.csv 和 findings.md。保留统计口径、客户编号与核对记录，供下游编写简报。": "Write summary.csv and findings.md in the result directory. Include statistical definitions, customer IDs, and verification records for the downstream brief writer.",
  "读取 Result 中的 findings.md 与 summary.csv，依据统计结果组织简报。": "Read findings.md and summary.csv from the result and organize the brief around the statistics.",
  "Result · 统计文件": "Result · Statistics files",
  " 将审核意见写入 review.md。": " Write review feedback to review.md."
} as const
