import { t } from '@agentflow/core/localization'
export const TUTORIAL_PROJECT_ID = 'agentflow-tutorial-weekly-brief'
export const TUTORIAL_GRAPH_ID = 'agentflow-tutorial-weekly-brief-flow'
export function TUTORIAL_DESCRIPTION() { return t("Turn these 8 customer interviews into a one-page weekly brief: plan the analysis and outline, then read the CSV to calculate topic counts, average ratings, and low-rating feedback. Save the statistics, check the results, and write the key findings and two actions for next week.") }
export function TUTORIAL_BRIEF() { return t("# Customer feedback · Weekly meeting brief\n\nFriday’s meeting needs a one-page brief to help the customer success team choose next week’s priorities.\n- Source: 8 customer interviews, rated 1–5, with 5 the highest.\n- Include an overview, key issues, and two actions for next week.\n- Cite customer IDs and distinguish observations from recommendations.\n- Keep all statistics traceable to the source table and include sample sizes.") }
export function TUTORIAL_CSV() { return t("Customer ID,Topic,Rating,Feedback\nC01,Response time,3,Slow replies during peak hours\nC02,Training materials,4,Clear introductory guide but more examples would help\nC03,Response time,2,Long wait for urgent issues\nC04,Process clarity,3,Unclear who received the escalated issue\nC05,Training materials,5,Video tutorials are very helpful\nC06,Response time,3,Would like estimated response times\nC07,Process clarity,4,Progress updates are generally timely\nC08,Training materials,4,Would like a frequently asked questions index") }

export const tutorialOutputs: Record<string, string> = {
  get analyst() { return t("## Analysis plan\n\n1. Check all 8 interviews and the 1–5 rating range.\n2. Calculate the overall average, topic counts, and number of ratings at or below 3.\n3. Keep customer IDs with each finding for review.\n4. Organize the brief into an overview, customer feedback, and next week’s actions.") },
  get writer() { return t("## Draft outline\n\nTitle: Weekly customer feedback brief.\n\n- Opening: Average rating and the week’s main issues.\n- Middle: Customer feedback by topic.\n- Closing: Two actions for next week.\n\nKeep it to one page, with conclusions followed by evidence.") },
  get reviewer() { return t("## Review\n\nThe outline covers ratings, topics, and actions. Add three details:\n\n1. Show the sample size and 1–5 scale beside the average.\n2. Retain customer IDs to trace feedback to the source.\n3. Separate actual feedback from recommendations.") },
  get reviser() { return t("## Revised outline\n\n- Overview: 8 interviews, a 1–5 scale, and the average rating.\n- Topic distribution: Counts must total 8.\n- Customer feedback: Retain IDs and explain ratings at or below 3.\n- Next week: Propose two actions and suggested owners for the meeting to confirm.") },
  get result() { return t("# findings.md\n\n## Statistics\n- Interviews: 8.\n- Average rating: 3.50 / 5 (28 ÷ 8).\n- Ratings at or below 3: 4, or 50%.\n\n| Topic | Interviews | Average rating |\n| --- | ---: | ---: |\n| Response time | 3 | 2.67 |\n| Training materials | 3 | 4.33 |\n| Process clarity | 2 | 3.50 |\n\n## Source evidence\nC01, C03, and C06 mention waiting or estimated response times. C04 wants to know who handles an escalated issue. C02 and C08 ask for examples and an FAQ index.\n\n## Verification\nPython read 8 rows; topic counts total 3 + 3 + 2 = 8; ratings total 28.\nOutput files: summary.csv and findings.md.") },
  get delivery() { return t("# Weekly customer feedback brief\n\nThis week’s **8 interviews** have an average rating of **3.50 / 5**; 4 ratings are at or below 3. Ratings use a 1–5 scale, with 5 the highest.\n\n## Key findings\n- **Response time needs priority attention**: 3 interviews averaging 2.67. C01, C03, and C06 want shorter waits or estimated response times.\n- **Training materials are well received**: 3 interviews averaging 4.33. C02 and C08 request examples and an index.\n- **Issue handoffs could be clearer**: 2 interviews averaging 3.50. C04 wants to know the current owner.\n\n## Proposed actions for next week\n1. The support lead should trial response-time estimates and owner indicators, then review feedback next week.\n2. The training owner should add a common example and FAQ index, then gather feedback in the next interviews.\n\nSource: customer-feedback.csv → summary.csv / findings.md.") }
}
