const assert = require('node:assert/strict')
const { mkdtempSync, cpSync, writeFileSync, readFileSync, existsSync, rmSync, mkdirSync } = require('node:fs')
const { tmpdir } = require('node:os')
const { basename, dirname, join, resolve } = require('node:path')
const { spawnSync } = require('node:child_process')
const root = mkdtempSync(join(tmpdir(), 'agentflow-host-'))
const repository = resolve(__dirname, '..')
const env = { ...process.env }
delete env.INIT_CWD
delete env.NODE_PATH

try {
  cpSync(join(repository, 'dist/skills/agentflow'), join(root, 'skill'), { recursive: true })
  const cli = join(root, 'skill/scripts/agentflow.mjs')
  const graph = join(root, 'skill/assets/review-flow.json')
  const call = (args, failure = false) => {
    const result = spawnSync(process.execPath, [cli, ...args], { cwd: root, env, encoding: 'utf8', windowsHide: true, timeout: 20_000 })
    if (failure) { assert.notEqual(result.status, 0); return result.stderr }
    assert.equal(result.status, 0, result.stderr || String(result.error))
    return JSON.parse(result.stdout)
  }
  assert.equal(call(['host', 'validate', graph]).valid, true)
  const runDir = join(root, '流程 with spaces')
  let state = call(['host', 'start', graph, '--workspace', root, '--run-dir', runDir])
  assert.deepEqual(state.ready, ['writer'])
  call(['host', 'next', runDir, '--node', 'reviser'], true)
  const task = call(['host', 'next', runDir])
  assert.equal(task.node.id, 'writer')
  assert.equal(call(['host', 'request', runDir, task.task.id]).task.id, task.task.id)
  writeFileSync(task.resultPath, 'Test fixture: draft text.\n')
  state = call(['host', 'submit', runDir, task.task.id, '--file', task.resultPath])
  assert.deepEqual(state.ready, ['reviewer'])
  const repeat = call(['host', 'submit', runDir, task.task.id, '--file', task.resultPath])
  assert.equal(repeat.artifacts.length, state.artifacts.length)
  writeFileSync(task.resultPath, 'Cannot overwrite accepted text.')
  call(['host', 'submit', runDir, task.task.id, '--file', task.resultPath], true)
  let review = call(['host', 'next', runDir])
  assert.ok(JSON.stringify(review.messages).includes('draft text'))
  call(['host', 'fail', runDir, review.task.id, '--reason', 'Deliberate test interruption'])
  assert.equal(call(['host', 'status', runDir]).status, 'blocked')
  const priorTask = review.task.id
  review = call(['host', 'retry', runDir, 'reviewer'])
  assert.equal(review.task.attempt, 2)
  writeFileSync(review.resultPath, 'Test fixture: review text.')
  call(['host', 'submit', runDir, priorTask, '--file', review.resultPath], true)
  call(['host', 'submit', runDir, review.task.id, '--file', review.resultPath])
  const final = call(['host', 'next', runDir])
  assert.equal(final.upstream.length, 2)
  writeFileSync(final.resultPath, 'Test fixture: final text.')
  state = call(['host', 'submit', runDir, final.task.id, '--file', final.resultPath])
  assert.equal(state.status, 'completed')
  assert.equal(call(['host', 'next', runDir]).task, null)
  assert.equal(readFileSync(state.artifacts.find(a => a.nodeId === 'reviser').path, 'utf8'), 'Test fixture: final text.')
  const panel = join(root, 'panel.html')
  assert.equal(call(['host', 'panel', runDir, '--out', panel]).mode, 'run-snapshot')
  assert.ok(readFileSync(panel, 'utf8').includes('final text'))
  call(['host', 'panel', graph, '--out', panel], true)
  const injection = JSON.parse(readFileSync(graph, 'utf8'))
  injection.name = '</script><script>globalThis.injected=true</script>'
  writeFileSync(join(root, 'injection.json'), JSON.stringify(injection))
  call(['host', 'panel', 'injection.json', '--out', 'injection.html'])
  assert.ok(!readFileSync(join(root, 'injection.html'), 'utf8').includes(injection.name))
  writeFileSync(join(runDir, '.lock'), '{"pid":0}')
  assert.match(call(['host', 'next', runDir], true), /locked/)
  assert.equal(call(['host', 'status', runDir]).status, 'completed')
  const checksum = JSON.parse(readFileSync(join(runDir, 'state.json'), 'utf8'))
  checksum.run.graph.goal = 'Edited runtime state'
  writeFileSync(join(runDir, 'state.json'), JSON.stringify(checksum))
  assert.match(call(['host', 'status', runDir], true), /Invalid or edited/)
  const project = join(root, 'project')
  mkdirSync(project)
  const install = spawnSync(process.execPath, [join(repository, 'scripts/install-skill.mjs'), '--host', 'both', '--project', project], { encoding: 'utf8', windowsHide: true, timeout: 20_000 })
  assert.equal(install.status, 0, install.stderr)
  for (const host of ['.agents', '.claude']) assert.ok(existsSync(join(project, host, 'skills/agentflow/scripts/agentflow-runtime.mjs')))
  const secondInstall = spawnSync(process.execPath, [join(repository, 'scripts/install-skill.mjs'), '--host', 'both', '--project', project], { encoding: 'utf8', windowsHide: true, timeout: 20_000 })
  assert.notEqual(secondInstall.status, 0)
  console.log('Standalone host skill: dependency ordering, recovery, retry, lineage, immutable results, panels, locks, corruption checks, and both install targets passed.')
} finally {
  if (dirname(root) === resolve(tmpdir()) && basename(root).startsWith('agentflow-host-')) rmSync(root, { recursive: true, force: true })
}
